// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Create as $Create} from "@wailsio/runtime";

export class PetObject {

    /** Creates a new PetObject instance. */
    constructor($$source: Partial<PetObject> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PetObject instance from a string or object.
     */
    static createFrom($$source: any = {}): PetObject {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PetObject($$parsedSource as Partial<PetObject>);
    }
}
