// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Create as $Create} from "@wailsio/runtime";

export class Bound {
    "X": number;
    "Y": number;
    "Width": number;
    "Height": number;

    /** Creates a new Bound instance. */
    constructor($$source: Partial<Bound> = {}) {
        if (!("X" in $$source)) {
            this["X"] = 0;
        }
        if (!("Y" in $$source)) {
            this["Y"] = 0;
        }
        if (!("Width" in $$source)) {
            this["Width"] = 0;
        }
        if (!("Height" in $$source)) {
            this["Height"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Bound instance from a string or object.
     */
    static createFrom($$source: any = {}): Bound {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Bound($$parsedSource as Partial<Bound>);
    }
}

export class Pet {

    /** Creates a new Pet instance. */
    constructor($$source: Partial<Pet> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Pet instance from a string or object.
     */
    static createFrom($$source: any = {}): Pet {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Pet($$parsedSource as Partial<Pet>);
    }
}
