// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call, Create as $Create} from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function GetScreenBounds(): Promise<$models.Bound> & { cancel(): void } {
    let $resultPromise = $Call.ByID(1946154527) as any;
    let $typingPromise = $resultPromise.then(($result: any) => {
        return $$createType0($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

export function GetState(): Promise<string> & { cancel(): void } {
    let $resultPromise = $Call.ByID(3830232807) as any;
    return $resultPromise;
}

export function SetAction(action: string): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(2791060436, action) as any;
    return $resultPromise;
}

export function Update(): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(2452365135) as any;
    return $resultPromise;
}

// Private type creation functions
const $$createType0 = $models.Bound.createFrom;
