// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Create as $Create} from "@wailsio/runtime";

export class PetService {

    /** Creates a new PetService instance. */
    constructor($$source: Partial<PetService> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PetService instance from a string or object.
     */
    static createFrom($$source: any = {}): PetService {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PetService($$parsedSource as Partial<PetService>);
    }
}
