// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call, Create as $Create} from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function GetImagePathByName(name: string): Promise<string> & { cancel(): void } {
    let $resultPromise = $Call.ByID(3168491500, name) as any;
    return $resultPromise;
}

export function GetPetNames(): Promise<string[]> & { cancel(): void } {
    let $resultPromise = $Call.ByID(3047208915) as any;
    let $typingPromise = $resultPromise.then(($result: any) => {
        return $$createType0($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

export function NewPet(): Promise<$models.PetService | null> & { cancel(): void } {
    let $resultPromise = $Call.ByID(3802732879) as any;
    let $typingPromise = $resultPromise.then(($result: any) => {
        return $$createType2($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = $models.PetService.createFrom;
const $$createType2 = $Create.Nullable($$createType1);
